### ISSUE TITLE
Getting warning ins the response suddenly

### ISSUE THREAD

**Issue by mattiasavelin** [dipankarmaikap/wp-sitemap-rest-api#1]
Hi! 

I'm getting warnings in the response (making the json invalid). 
```
<br />
<b>Warning</b>:  Undefined array key "pageNo" in <b>/www/tandlakaresecmsb_276/public/wp-content/plugins/wp-sitemap-rest-api-main/wp-sitemap-rest-api.php</b> on line <b>16</b><br />
<br />
<b>Warning</b>:  Undefined array key "taxonomyType" in <b>/www/tandlakaresecmsb_276/public/wp-content/plugins/wp-sitemap-rest-api-main/wp-sitemap-rest-api.php</b> on line <b>18</b><br />
```

I can "work around" it by adding the query params `pageNo`& `taxonomyType` but with empty values. I'm guessing this is not quite the intended behaviour. 🙂

**Comment by dipankarmaikap** [comment]
by default it will fetch the category, and its not required to provide those query params. I have tested and its working as intended.
